export {Button, FixedWidthButton} from "./Button";
export {default as Avator} from "./Avator";
export {HomeSlider,CategoriesSlider,ProductImgSlider} from "./Slider";
export {default as ErrorModal} from "./Modal/ErrorModal";
export {default as AddCartModal} from "./Modal/AddCartModal";
export {default as Pagination} from "./pagination";
export {default as HomeAnimation} from "./HomeAnimation";
export {default as TextLoader} from "./Loader/TextLoader";
export {default as LinearBar} from "./Loader/LinearBar";
export {BasicToastr, ModalToastr} from "./Toast/index";